include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/core/data/isar/*.g.dart
  errors:
    experimental_member_use: ignore
    non_const_argument_for_const_parameter: ignore

linter:
  rules:
    use_null_aware_elements: false
